export const ROUTES = {
  HOME: '/',
  JOURNAL: '/journal',
  MASTERS: '/masters',
  REPORTS: '/reports',
  ACCOUNT: '/account',
  SALES: '/sales',
  SALES_RETURN: '/sales-return',
  PURCHASE: '/purchase',
  PURCHASE_RETURN: '/purchase-return',
  ITEM_ADD: '/item-add',
  ITEM_GROUP: '/item-group',
  USER_ADD: '/user-add',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  EDIT_PROFILE: 'edit-profile',
  LANDING: '/landing',
  ITEM_REPORT: 'item-report',
  SALES_REPORT: 'sales-report',
  PURCHASE_REPORT: 'purchase-report',
  PNL_REPORT: 'pnl-report',
  BUSINESS_INFO: '/bus-info',
  BUSINESS_ADDRESS: '/bus-address',
};
